apiVersion: apps/v1
kind: Deployment
metadata:
  name: maie-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maie
  template:
    metadata:
      labels:
        app: maie
    spec:
      containers:
        - name: maie-app
          image: maie:latest
          ports:
            - containerPort: 8000
